### ISSUE TITLE
Repeated phrases in mnemonics might be dropped together

### ISSUE THREAD

**Issue by stmharry** [hashgreen/hoogii-wallet#103]
As implemented here:
https://github.com/hashgreen/hoogii-wallet/blob/99f5d7b67df296eb8f2137200fe7d57d1c32cf77/src/tabs/pages/mnemonic/createMnemonic.tsx#L29

As BIP-39 does not prohibit repeated phrases, mnemonics like `abandon abandon abandon ...` can exist, and if the implementation selects `abandon` as the phrase to drop, all instances of `abandon` will be dropped. I recommend, thus, dropping phrases by their indices.

Below is a reference implementation

```js
import { shuffle } from 'lodash';

const size = mnemonics.length;
const indices = Array.from({ length: size }, (_, i) => i);
shuffle(indices);

const emptyIndices = indices.slice(0, isDev ? 1 : 6);
const defaultValues = mnemonics.map((phrase, index) => (emptyIndices.includes(index) ? "" : phrase));

console.log(defaultValues);
```

**Comment by hryjosn** [comment]
Hi @stmharry, thanks for finding this issue, and we will fix and update it soon

**Comment by hryjosn** [comment]
@stmharry Fixed
Good catch!
