### ISSUE TITLE
[Suggestion] Mnemonic Order

### ISSUE THREAD

**Issue by Ganbin** [hashgreen/hoogii-wallet#115]
I wanted to create an account on Hoogii, but got confused by the mnemonic order.

It is a grid of 12x3

Do I have to read 

1 - 2 - 3
4 - 5 - 6
...

or 

1 - 9 - 17
2 - 10 - 18
...

I suppose the second one but not sure of it.

I think adding the number before each word would be great.

**Comment by ahwei** [comment]
thank you for your suggestion. The correct order is 1 - 2 - 3. 
We will add your suggestion to the future optimization list. Thank you.
